-- Drops all tables (removes Book Rater database from user)

DROP TABLE IF EXISTS Authors CASCADE;
DROP TABLE IF EXISTS Books CASCADE;
DROP TABLE IF EXISTS Genres CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Readers CASCADE;
DROP TABLE IF EXISTS Has_genre;
DROP TABLE IF EXISTS Favorite_book;
DROP TABLE IF EXISTS Favorite_author;
DROP TABLE IF EXISTS Favorite_genre;
DROP TABLE IF EXISTS Reads;
DROP TABLE IF EXISTS Rates;